// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgfmfzkmxjxvzwkrdfyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZm1memtteGp4dnp3a3JkZnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzY4MDUsImV4cCI6MjA3MDkxMjgwNX0.rRpmJ6MIJomzFBJIIJwSWzDX8eJZeBZb36j1eUdbDKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});