name: Build for TrueHost

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: truehost-ready-files
        path: dist/
        retention-days: 30

    - name: Create deployment zip
      run: |
        cd dist
        zip -r ../truehost-deployment.zip .
        
    - name: Upload deployment zip
      uses: actions/upload-artifact@v4
      with:
        name: truehost-deployment-zip
        path: truehost-deployment.zip
        retention-days: 30